version: '0.0.1'

services:

  backend:
    build: ./services/backend
    ports:
      - 5001:5001
    volumes:
      - ./services/backend:/app
      - ../../out/data-crawler/:/app/out/data-crawler
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5001

  frontend:
    restart: always
    env_file:
      - .env
    build: ./services/frontend
    ports:
      - 8000:8080
    depends_on:
      - backend
    links:
      - backend
